# Example configuration for ingesting financial transactions from Kafka to Delta Lake on S3

kafka:
  bootstrap_servers: "broker1:9092,broker2:9092,broker3:9092"
  topic: "financial-transactions"
  consumer_group: "delta-ingest-transactions"
  security_protocol: "SASL_SSL"
  sasl_mechanisms: "PLAIN"
  sasl_username: "${KAFKA_USERNAME}"
  sasl_password: "${KAFKA_PASSWORD}"
  auto_offset_reset: "earliest"
  session_timeout_ms: 45000
  heartbeat_interval_ms: 3000
  max_poll_records: 500

s3:
  bucket: "financial-data-lake"
  region: "us-west-2"
  prefix: "transactions"

delta:
  table_name: "transactions"
  write_mode: "append"
  merge_schema: true
  overwrite_schema: false
  partition_columns:
    - "transaction_date"
    - "currency"
  schema:
    - name: "transaction_id"
      data_type: "utf8"
      nullable: false
    - name: "account_id"
      data_type: "utf8"
      nullable: false
    - name: "transaction_type"
      data_type: "utf8"
      nullable: false
    - name: "amount"
      data_type: "decimal128"
      nullable: false
    - name: "currency"
      data_type: "utf8"
      nullable: false
    - name: "transaction_timestamp"
      data_type: "timestamp_millisecond"
      nullable: false
    - name: "transaction_date"
      data_type: "date32"
      nullable: false
    - name: "merchant_id"
      data_type: "utf8"
      nullable: true
    - name: "merchant_name"
      data_type: "utf8"
      nullable: true
    - name: "merchant_category"
      data_type: "utf8"
      nullable: true
    - name: "description"
      data_type: "utf8"
      nullable: true
    - name: "reference_number"
      data_type: "utf8"
      nullable: true
    - name: "status"
      data_type: "utf8"
      nullable: false
    - name: "fees"
      data_type: "decimal128"
      nullable: true
    - name: "exchange_rate"
      data_type: "float64"
      nullable: true

processing:
  batch_size: 500
  batch_timeout_ms: 20000
  max_retries: 5
  retry_delay_ms: 2000
  enable_compression: true
  compression_type: "zstd"
  enable_metrics: true
  checkpoint_interval_ms: 30000